#indica la version de Docker Compose utilizada
version: '3.7'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - 6379:6379
    networks:
      - my-network

  app-web1:       #nombre del servicio
    image: enmanuelcruzdejesus/barcamp-app-docker #imagen utilizada.
    ports:          #puertos que estaran expuestos.
      - 8080:8080
    environment:    #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/Barcampdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - spring.redis.host=redis

    networks:    #red para conectar los equipos.
      - my-network
    volumes:
      - my-vol:/tmp/
    depends_on:   #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
      - redis

  app-web2: #nombre del servicio
    image: enmanuelcruzdejesus/barcamp-app-docker #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 8081:8080
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/Barcampdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - spring.redis.host=redis

    networks: #red para conectar los equipos.
      - my-network
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
      - redis

  app-web3: #nombre del servicio
    image: enmanuelcruzdejesus/barcamp-app-docker #imagen utilizada.
    ports: #puertos que estaran expuestos.
      - 8082:8080
    environment: #variable de ambiente
      - spring.datasource.url=jdbc:mysql://base-datos-app-web:3306/Barcampdb
      - spring.datasource.username=root
      - spring.datasource.password=entrada01
      - spring.redis.host=redis

    networks: #red para conectar los equipos.
      - my-network
    volumes:
      - my-vol:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
      - redis



  base-datos-app-web:
    image: mysql
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=entrada01
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=entrada01
      - MYSQL_DATABASE=Barcampdb
    volumes:   #volumen de datos utilizado.
      - ~/mydb:/var/lib/mysql
    networks:
      - my-network

  angular:
    image: enmanuelcruzdejesus/barcamp-front
    container_name: angular
    ports:
      - 80:90
    depends_on:
      - app-web1
    networks:
      - my-network

#  haproxy:
#   image: tutum/haproxy:0.2
#   ports:
#    - 90:80
#    - 1936:1936
#   depends_on:
#    - app-web1
#    - app-web2
#    - app-web3




networks:  #bloque para las redes
  my-network:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  my-vol:
